server:
  servlet:
    context-path: /api
  port: 8080

spring:
  app:
    jwt-token:
      access: jkd8723hjkfd8723jkfds8723hfds8723hfds8723jkfd8237hfds8723h

  security:
    user:
      password: tD54'kS+Z*kw4:XR

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: hanjsbnjasaskmflvasdda
    url: jdbc:postgresql://188.120.227.37:5432/docroom
    auto-commit: false
    maximum-pool-size: 5
    leak-detection-threshold: 120000
    max-lifetime: 120000
    idle-timeout: 60000
    isolate-internal-queries: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
  web:
    throw-exception-if-no-handler-found: true

aes:
  key: iopasduitghjqwee
