server:
  servlet:
    context-path: /api
  port: 8080

spring:
  profiles:
    active: dev

  app:
    jwt-token:
      access:

  security:
    user:
      password:

  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    url:
    auto-commit: false
    maximum-pool-size: 5
    leak-detection-threshold: 120000
    max-lifetime: 120000
    idle-timeout: 60000
    isolate-internal-queries: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
  web:
    throw-exception-if-no-handler-found: true

file:
  storage: storage/images
  max-size: 5242880 # 5MB

aes:
  key: